LOBBY_ADJECTIVES = [
    'Friendly',
    'Sad',
    'Brave',
    'Clever',
    'Slow',
    'Keen',
    'Scared',
    'Triangular',
    'Round',
    'Fiery',
    'Quiet',
    'Flaming',
    'Dead',
    'Self-conscious',
    'Proud',
    'Drowned',
    'Abused',
    'Optimistic',
    'Cheery',
    'Emotional',
    'Sensitive',
    'Quick',
    'Reliable',
    'Manly',
    'Posh',
]

LOBBY_NOUNS = [
    'Anaconda',
    'Python',
    'Cobra',
    'Snek',
    'Rattlesnek',
    'Boa',
    'Viper',
    'Rainbow boa',
    'Lizard',
    'Serpent',
    'Mamba',
    'Tarantula',
    'King Cobra',
    'Tiger Snake',
    'south American Bushmaster',
    'Mozambique Spitting Cobra',
    'Krait',
    'Viper'
]
