LOBBY_ADJECTIVES = [
    'Friendly',
    'Sad',
    'Brave',
    'Clever',
    'Slow',
    'Keen',
    'Scared',
    'Triangular',
    'Round',
    'Fiery',
    'Quiet',
    'Flaming',
    'Dead',
    'Self-conscious',
    'Proud',
    'Drowned',
    'Abused',
    'Optimistic',
    'Cheery',
    'Emotional',
    'Sensitive',
    'Quick',
    'Reliable',
    'Manly',
    'Posh',
    'Pointy',
]

LOBBY_NOUNS = [
    'Triangle',
    'Square',
    'Circle',
    'Polygon',
    'Oblong',
    'Rectangle',
    'Two-Dimensional Cube',
    'Two-Dimensional Sphere',
    'Ellipse',
    'Hexagon',
    'Dodecahedron',
]
