LOBBY_ADJECTIVES = [
    'friendly',
    'sad',
    'brave',
    'clever',
    'slow',
    'keen',
    'scared',
    'triangular',
    'round',
    'fiery',
    'quiet',
    'flaming',
    'dead',
    'not a dead',
    'self-conscious',
    'proud',
    'drowned',
    'abused',
    'optimistic',
    'cheery',
    'emotional',
    'sensitive',
    'quick',
    'reliable',
    'manly',
    'posh',
]

LOBBY_NOUNS = [
    'anaconda',
    'python',
    'cobra',
    'snek',
    'rattlesnek',
    'boa',
    'viper',
    'rainbow boa',
    'lizard',
    'serpent',
    'mamba',
    'tarantula',
    'king cobra',
    'tiger snake',
    'South American bushmaster',
    'Mozambique spitting cobra',
    'krait',
    'viper'
]
